import { TRPCReactProvider } from "@/trpc/client";
import type { Metadata } from "next";
import { Geist_Mono, Space_Grotesk } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { Providers } from "./provider";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <Providers>
        <html lang="en">
          <body
            className={`${geistMono.variable} ${spaceGrotesk.variable} font-sans antialiased`}
          >
            <Toaster />
            {children}
          </body>
        </html>
      </Providers>
    </TRPCReactProvider>
  );
}
